README.md, Tests/Get-PASOnboardingRule.Tests.ps1, Tests/Get-PASPSMConnectionParameter.Tests.ps1, Tests/Import-PASPlatform.Tests.ps1, Tests/New-DynamicParam.Tests.ps1, Tests/New-PASOnboardingRule.Tests.ps1, Tests/Resume-PASPSMSession.Tests.ps1, Tests/Suspend-PASPSMSession.Tests.ps1, appveyor.yml, build/test.ps1, psPAS/Functions/Connections/Get-PASPSMConnectionParameter.ps1, psPAS/Functions/Monitoring/Resume-PASPSMSession.ps1, psPAS/Functions/Monitoring/Suspend-PASPSMSession.ps1, psPAS/Functions/OnboardingRules/Get-PASOnboardingRule.ps1, psPAS/Functions/OnboardingRules/New-PASOnboardingRule.ps1, psPAS/Functions/Platforms/Import-PASPlatform.ps1, psPAS/Private/Get-PASParameter.ps1, psPAS/Private/Invoke-PASRestMethod.ps1, psPAS/about_psPAS.help.txt, psPAS/about_psPAS_Versions.help.txt, psPAS/psPAS.Format.ps1xml, psPAS/psPAS.psd1
Update to module to include CyberArk 10.2 functionality
This PR implements the following features:
100% Code Coverage through Pester Tests
New-PASOnboardingRule has added parameters available from 10.2 onwards. The 9.8 & 10.2 parameters are configured as separate parametersets.
Get-PASOnboardingRule has a new parameter added, allowing search of Onboarding rules by name in version 10.2
Import-PASPlatform function added, allowing import of CPM Platforms
Get-PASPSMConnectionParameters updated to facilitate return of HTML5 connection data when PSMGW is configured.
Suspend-PASPSMSession & Resume-PASPSMSession functions added, expanding on the automatic mitigation capability for PSM Sessions.
Updates default view for OnboardingRule.
New Badges for the Readme.
Explain the motivation for making …
=> Feature 10 2

psPAS/Private/Invoke-PASRestMethod.ps1
This PR fixes the following bug that is only reproducible in PowerShell Core:
```
$vaultToken | Get-PASAccount -Keywords $userName
The format of value '{{ Base64 String }}' is invalid.
At C:\Program Files\PowerShell\Modules\psPAS\1.2.3\Functions\Accounts\Get-PASAccount.ps1:151 char:13
+ ...   $result = Invoke-PASRestMethod -Uri $URI -Method GET -Headers $sess ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-PASRestMethod
```
Such behavior is caused by the following breaking change in PowerShell Core:
* Strict RFC header parsing is now default for the `-Headers` and `-UserAgent` parameter. This can …
=> Bypass strict RFC header parsing in PS Core

Tests/Invoke-PASRestMethod.Tests.ps1, Tests/New-PASSession.Tests.ps1, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Private/Invoke-PASRestMethod.ps1
Return value for authentication using the version 10 api differs from version 9.
Version 9 returns the token as the value of the CyberArkLogonResult property.
Version 10 returns the raw value with no property.
Logon process updated to include the additional parameters and URL endpoint for version 10.
If Invoke-PASRestMethod is called from New-PASSession, and the raw value is returned (i.e. its a version 10 authentication request), the return value will be added to the CyberArkLogonResult property.
Additional exception handling added to cater for failures related to v10 endpoint being used with a v9 solution.
Updates logon process to cater for V10 API
This PR fixes/implements the following **bugs**:
LDAP authentication from the module to CyberArk 10.3
_Explain the **motivation** for making …
=> UPDATE Logon Process

CHANGELOG.md, appveyor.yml, psPAS/Functions/Platforms/Export-PASPlatform.ps1
Fixes issue where Export-PASPlatform was not creating ZIP archives in the correct way.
This PR fixes the following **bug**:
Call to set-content was creating an invalid ZIP archive. Code now corrected and valid files are being produced.
Tested in Both PowerShell 5 & PSCore 6.1. Confirmed that exported platforms are valid ZIP files and have the expected content.
Closes #86
=> Issue 86 - FIX Export-PASPlatform File Creation

CHANGELOG.md, psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/Functions/Accounts/Get-PASAccountPassword.ps1
Adds pipeline support for version 10 when piping `Get-PASAccount` into `Get-PASAccountPassword`
This PR fixes/implements the following **bugs/features**:
ADD  parameter validation to `Get-PASAccount`
ADD parameter alias for "id" to Get-PASAccountPassword
UPDATE help for `limit` parameter in Get-PASAccount`
Closes #100 #101
=> FIX issues 100 + 101

Tests/New-PASSession.Tests.ps1, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Private/Invoke-PASRestMethod.ps1
This PR implements the following features:
Allow for Integrated Auth when Logon type is Windows
Need to pass -UseDefaultCredentials to use integrated Windows Authentication
Test New Feature
_$test = New-PASSession -type Windows -BaseURI 'myuri'_
Regression
_$test = New-PASSession -UseV9API -Credential (Get-Credential) -BaseURI 'myuri' -connectionNumber 22_
_$account = $test | Get-PASAccount -search "mine"_
N/A
=> Implement Windows Integrated Auth

CHANGELOG.md, README.md, Tests/Add-PASDiscoveredAccount.Tests.ps1, Tests/Connect-PASPSMSession.Tests.ps1, Tests/Get-PASAccountGroup.Tests.ps1, Tests/Get-PASDirectory.Tests.ps1, Tests/Get-PASGroup.Tests.ps1, Tests/Get-PASPSMConnectionParameter.Tests.ps1, Tests/New-PASSession.Tests.ps1, Tests/Remove-PASGroupMember.Tests.ps1, Tests/Set-PASOnboardingRule.Tests.ps1, appveyor.yml, psPAS/Functions/AccountGroups/Get-PASAccountGroup.ps1, psPAS/Functions/Accounts/Add-PASDiscoveredAccount.ps1, psPAS/Functions/Connections/Get-PASPSMConnectionParameter.ps1, psPAS/Functions/LDAPDirectories/Get-PASDirectory.ps1, psPAS/Functions/Monitoring/Connect-PASPSMSession.ps1, psPAS/Functions/OnboardingRules/Set-PASOnboardingRule.ps1, psPAS/Functions/User/Get-PASGroup.ps1, psPAS/Functions/User/Remove-PASGroupMember.ps1, psPAS/Private/Invoke-PASRestMethod.ps1, psPAS/psPAS.CyberArk.Vault.Group.Formats.ps1xml, psPAS/psPAS.psd1
Includes support for CyberArk 10.5 features:
- Remove Group Members
- Get Groups
- Add Discovered Accounts
- Monitor Active PSM Session
- Update Automatic Onboarding Rule
- Get LDAP Directory by Name
- Get Safe Account Groups
- Connect with PSM (for Ad-Hoc Connections)
Also now explicitly specifies that TLS 1.2 is used for web requests when using PSCore.
Developed and tested against 10.5 API.
Pester Tests updated or created where necessary
Closes #109 #111
=> CyberArk 10.5 Features

psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/Functions/Safes/Get-PASSafe.ps1, psPAS/Private/Invoke-PASRestMethod.ps1, psPAS/psPAS.psd1
This PR fixes/implements the following **bugs/features**:
Fixes #144 
Fixes #142 
With the addition of the nextLink loop, the original uses of 'limit' and 'offset' are essentially invalidated.  There's not many real-world applications of these query parameters outside of pagination, so I believe this is an improvement on the parameters.  This caveat has been mentioned in the documentation fo Get-PASAccount.
Verify Get-PASAccount returns more than 100 results, implementing the nextLink return value:
```$Test = $Token | Get-PASAccount -Verbose```
Verify Get-PASAccount returns more than 100 results, implementing the nextLink return value, and retains original query:
```$Test = $Token | Get-PASAccount -Verbose -limit 10 -offset 4 -search E```
Verify Get-PASSafe respects the TimeoutSec and …
=> Splat -TimeoutSec, Implement account pagination

Tests/Get-PASAccount.Tests.ps1, psPAS/Functions/Applications/Add-PASApplication.ps1
This PR fixes the following **bugs**:
Changes type of parameter `BusinessOwnerPhone` in `Add-PASApplication` to `[string]`
Can add application & specify phone number without issue
````powershell
$token | Add-PASApplication -AppID SomeNewApp -Description "App Description" -BusinessOwnerPhone 123456 -Location "\SomeLocation"
````
Closes #149
=> Fix Issue 149

psPAS/Functions/LDAPDirectories/Add-PASDirectory.ps1
This PR fixes/implements the following **bugs/features**:
The "SSLConnect" parameter is required if adding LDAPS hosts. Without it, the following error is returned:
"LDAP Directory can't contains diffrenet DCs with diffrenet ports/ssl configurations". 
Fixes #
Closes #
=> Add Add-LDAPDirectory SSLConnect Parameter

CHANGELOG.md, Tests/Get-PASAccountGroup.Tests.ps1, Tests/Get-PASAccountPassword.Tests.ps1, Tests/New-PASUser.Tests.ps1, Tests/Remove-PASAccount.Tests.ps1, psPAS/Functions/AccountGroups/Get-PASAccountGroup.ps1, psPAS/Functions/Accounts/Get-PASAccountPassword.ps1, psPAS/Functions/Accounts/Remove-PASAccount.ps1, psPAS/Functions/Applications/Get-PASApplication.ps1, psPAS/Functions/Applications/Get-PASApplicationAuthenticationMethod.ps1, psPAS/Functions/Applications/Remove-PASApplicationAuthenticationMethod.ps1, psPAS/Functions/User/New-PASUser.ps1, psPAS/Private/Get-PASParameter.ps1, psPAS/psPAS.psd1
- Changed Parameter `UseV9API` to `UseClassicAPI` in line with standard names for module parameters.
- Changed Parameter `UseV10API` to `UseClassicAPI` in line with standard module operation.
=> Standard Parameters

Tests/Invoke-PASRestMethod.Tests.ps1, Tests/New-PASSession.Tests.ps1, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Private/Invoke-PASRestMethod.ps1
Implements support for providing a Certificate Thumbprint when Client Certificate Authentication is configured.
- Client Certificate Authentication Support
- If IIS is configured to require certificates for authentication, details of a certificate thumbprint can be included in the initial authentication request to the api via `New-PASSession`.
This PR fixes the following **bugs**:
- Fixed Shared Authentication
- Returned session token is now made available to other module functions
- Previously, LogonResult property containing the session token would not have been saved.
After providing details of a certificate thumbprint during authentication, the certificate details are saved as expected to the WebSession available in the script scope.
This …
=> Add Client Certificate Authentication Support

Tests/Add-PASAccount.Tests.ps1, Tests/Close-PASSession.Tests.ps1, Tests/Get-PASSession.Tests.ps1, Tests/Remove-PASAccount.Tests.ps1, Tests/Remove-PASDirectory.Tests.ps1, Tests/Remove-PASGroupMember.Tests.ps1, Tests/Use-PASSession.Tests.ps1, psPAS/Functions/Authentication/Close-PASSession.ps1, psPAS/Functions/Authentication/Get-PASSession.ps1, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Functions/Authentication/Use-PASSession.ps1, psPAS/psPAS.psd1, psPAS/psPAS.psm1
Adds functions `Get-PASSession` & `Use-PASSession`
`Get-PASSession` is used to retrieve module scope variable values which are used to perform each request to the API.
`Use-PASSession` is used to set module scope variable values which are used to perform each request to the API.
This functionality allows the user to 
- store data related to multiple authenticated api sessions.
- switch the context of the authenticated session the module commands will interact with.
- obtain the values required to interact with the API using `invoke-RestMethod`.
=> Add Session Functions

CHANGELOG.md, psPAS/Functions/User/New-PASUser.ps1
- `New-PASUser`
- Added parameter `ChangePassOnNextLogon` to 10_9 parameterset.
- Removed `ChangePasswordOnTheNextLogon` from 10_9 parameterset.
- Fixes issue where `New-PASUser` was failing to set the change password at next logon flag for a new user.
=> Fix New-PASUser

Tests/Hide-SecretValue.Tests.ps1, Tests/Invoke-PASRestMethod.Tests.ps1, appveyor.yml, psPAS/Private/Hide-SecretValue.ps1, psPAS/Private/Invoke-PASRestMethod.ps1
Adds output to debug stream from `Invoke-PASRestMethod`
if Debug is enabled
- outputs request status code
- outputs request body (if present)
- if request body contains a value assumed to be secret, it is replaced with `"****"`
=> Add Debug Messages

Tests/Get-PASAccountPassword.Tests.ps1, Tests/Get-PASResponse.Tests.ps1, psPAS/Functions/Accounts/Get-PASAccountPassword.ps1, psPAS/Private/Get-PASResponse.ps1
Recent module updates meant password was not getting returned if querying the ClassicAPI.
- `Get-PASAccountPassword` updated to handle output of Get-PASResponse for both Classic & Version 10 API endpoint.
- `Get-PASResponse` updated to send the originally returned string, logic to remove opening & closing quotation marks moved into `Get-PASAccountPassword`.
=> FIX Get-PASccountPassword

CHANGELOG.md, psPAS/Functions/SafeMembers/Add-PASSafeMember.ps1, psPAS/Functions/SafeMembers/Get-PASSafeMember.ps1
- `Add-PASSafeMember`
- Added parameter aliases for permission name equivalent names returned from Get-PASSafeMember.
- `Get-PASSafeMember`
- Updated help text to detail permission name equivalents returned from the API.
No changes to function output.
New parameter aliases can be used, but request body remains the same as it is currently.
Closes #185
=> Issue-185 - Add Help Text & Aliases

CHANGELOG.md, README.md, psPAS/Functions/SafeMembers/Add-PASSafeMember.ps1, psPAS/Functions/SafeMembers/Get-PASSafeMember.ps1
- `Add-PASSafeMember`
- Added parameter aliases for permission name equivalent names returned from Get-PASSafeMember.
- `Get-PASSafeMember`
- Updated help text to detail permission name equivalents returned from the API.
Additional examples for CPM Operations added to README.
Closes #185
=> Update PASSafeMember Functions

CHANGELOG.md, psPAS/Functions/Accounts/Set-PASAccount.ps1
This PR fixes the following **bugs**:
Only check for `TypeName` of `$InputObject` if `$InputObject` exists.
Fixes non-terminating error when not piping an object into the function and using the Classic API.
No error raised when not piping an object into the function and using the Classic API.
=> FIX Set-PASAccount

CHANGELOG.md, psPAS/Functions/Authentication/New-PASSession.ps1
Updated to assign a response of 180 characters or more to the Authorization header element.
This PR fixes the following **bugs**:
Previously the API response was expected to be exactly 180 characters long if coming from the v10 API endpoint.
When authenticating from v9.x, but using v10 API endpoint (where available), the response could be longer than 180 characters. 
`New-PASSession` updated to expect a response of 180 characters or more.
Able to authenticate against the v10 endpoint using 9.95
Able to authenticate against the v10 endpoint using 10.x
Closes #189
=> FIX New-PASSession

psPAS/Functions/Accounts/Get-PASAccountPassword.ps1
Corrected parameter name to `TicketingSystem` from `TicketingSystemName`.
Closes #199
=> FIX Get-PASAccountPassword

Tests/New-PASSession.Tests.ps1, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Private/Invoke-PASRestMethod.ps1
Add Support for Responding to Radius Challenge
When Radius Authentication is configured in Challenge Mode, initial authentication request will raise a `ITATS542I` exception.
`New-PASSession` now catches this error, and submits the required value for the Radius challenge back to the API.
Added feature for Radius in "Append" mode to allow specification of custom delimiter when appending OTP to password value.
Confirmation of functionality: 
https://github.com/pspete/psPAS/issues/195#issuecomment-526147226
https://github.com/pspete/psPAS/issues/195#issuecomment-526307471
Pester tests updated to cover new code/features.
Closes #195
=> Add Feature - Radius Challenge Support

Tests/Invoke-PASRestMethod.Tests.ps1, Tests/Skip-CertificateCheck.Tests.ps1, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Private/Invoke-PASRestMethod.ps1, psPAS/Private/Out-PASFile.ps1, psPAS/Private/Skip-CertificateCheck.ps1, psPAS/Private/Test-IsCoreCLR.ps1
Adds `-SkipCertificateCheck` parameter to `New-PASSession`
`-SkipCertificateCheck` parameter added to `New-PASSession` & `Invoke-PASRestMethod`.
Allows a user to opt to not perform any validation of the SSL certificate securing the API.
`-SkipCertificateCheck` is passed on to `Invoke-PASRestMethod`. 
Added logic to allow bypass of SSL validation in both PWSH & PowerShell.
Broke my trust with certificate authority.
Developed the feature until I could use the features of the module without any SSL/TLS related issues in PWSH or PowerShell.
Fixes #
Closes #196
=> Introduce SkipCertificateCheck

CHANGELOG.md, README.md, docs/collections/_docs/00-install.md, psPAS/psPAS.psd1
Raising the minimum required version from 3.0, to 5.0.
Some instances of syntax which is not compatible with PowerShell versions earlier than v5 exist in the module. 
Relates to #207
=> UPDATE Minimum PowerShellVersion

Tests/Enable-PASCPMAutoManagement.Tests.ps1, psPAS/Functions/Accounts/Enable-PASCPMAutoManagement.ps1, psPAS/psPAS.psd1
Added new function `Enable-PASCPMAutoManagement`.
It is just a wrapper for Set-PASAccount, but performs 2 actions: 
- sets `/secretManagement/automaticManagementEnabled` to `$true`
- clears `/secretManagement/manualManagementReason`.
To enable an account for automatic CPM management, both actions must be performed.
Closes #217
=> ADD Enable-PASCPMAutoManagement

CHANGELOG.md, Tests/New-PASSession.Tests.ps1, docs/collections/_commands/New-PASSession.md, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Private/Invoke-PASRestMethod.ps1
Adds `Certificate` parameter to `New-PASSession`, allows client certificate to be specified and passed to Invoke-WebRequest for a secure web request.
=> Add Certificate Parameter

Tests/New-PASSession.Tests.ps1, docs/collections/_commands/New-PASSession.md, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Private/Invoke-PASRestMethod.ps1
Adds capability for Windows + RADIUS authentication.
- Passes `$Credential` value onto `Invoke-WebRequest` for Windows authentication, in addition to including in the JSON body.
- If initial IIS Windows authentication succeeds but does not return an authentication token, and if radius parameters are specified, submits the username & password, and subsequently the OTP to respond to any radius challenge.
- Adds prompt for OTP, after initial RADIUS authentication, if the value of the `$OTP` parameter is `passcode`.
- Adds condition to throw error if Windows authentication succeeds but does not result in a CyberArk authentication token being returned.
Pester tests updated & passing
Closes #245
=> Windows + RADIUS Auth

CHANGELOG.md, Tests/Add-PASAccount.Tests.ps1, docs/collections/_commands/Get-PASSafeMember.md, psPAS/Functions/Accounts/Add-PASAccount.ps1, psPAS/Functions/SafeMembers/Get-PASSafeMember.ps1, psPAS/Private/Invoke-PASRestMethod.ps1, psPAS/psPAS.psd1, psPAS/xml/psPAS.CyberArk.Vault.Directory.Formats.ps1xml
- Changes minimum required PowerShell version to 5.1
- Marginal performance improvement by suppressing progress bar for `Invoke-WebRequest`.
- `Add-PASAccount`
- Fixed bug where mandatory username parameter is not sent in the request body when using the classic API.
- `Get-PASDirectoryMapping`
- include MappingID in default table output
- `Get-PASSafeMember`
- Updated help text to clarify `MemberName` parameter and expected failure conditions due to request method (`PUT` instead of `GET`)
Closes #253 
Closes #257 
Closes #258
=> Version Release

CHANGELOG.md, Tests/Add-PASSafeMember.Tests.ps1, Tests/Get-PASSafeMember.Tests.ps1, Tests/Set-PASSafeMember.Tests.ps1, psPAS/Functions/SafeMembers/Add-PASSafeMember.ps1, psPAS/Functions/SafeMembers/Get-PASSafeMember.ps1, psPAS/Functions/SafeMembers/Set-PASSafeMember.ps1
Changes `Permissions` output of:
- `Get-PASSafeMember`
- `Set-PASSafeMember`
- `Add-PASSafeMember`
This PR fixes the following bug:
When added, set or queried, both the name & value of safe permissions is now returned as a nested property under `Permissions`.
Previously, only the name of any permissions configured with a value of `$true` was returned, contained as an array of the `Permissions` property.
Update allows integer value of `RequestsAuthorizationLevel` permission to be returned.
Pester tests updated to check that expected `boolean` or `int` permission property values 
#275
=> `*-PASSafeMember` Permission Output

Tests/Get-PASSAMLResponse.Tests.ps1, Tests/New-PASSession.Tests.ps1, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Private/Get-PASSAMLResponse.ps1
Adds SAML Auth support introduced to the api in 11.4.
- added new parameter `SAMLAuth`.
Adds new Private function `Get-PASSAMLResponse`, based on [this gist](https://gist.github.com/infamousjoeg/b44faa299ec3de65bdd1d3b8474b0649), which is designed to get the required saml response before attempting authentication.
Pester tests created based on expected output and logic flow
=> ADD SAML Authentication

Tests/New-PASSession.Tests.ps1, docs/collections/_commands/New-PASSession.md, docs/collections/_docs/01-authentication.md, psPAS/Functions/Authentication/New-PASSession.ps1
Provides any exception text returned from the RADIUS server as the prompt requesting the OTP value.
OTP parameter can now be omitted if OTP is unknown at time of initial authentication, the literal value "passcode" no longer needs to be provided.
Removed need for OTPMode parameter to have a value of "Challenge" in order to reach the OTP prompt. OTPMode can now be omitted.
Pester tests updated
#283
=> RADIUS Auth

CHANGELOG.md, Tests/ConvertTo-QueryString.Tests.ps1, Tests/Get-PASGroup.Tests.ps1, psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/Functions/Applications/Get-PASApplication.ps1, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Functions/EventSecurity/Get-PASPTAEvent.ps1, psPAS/Functions/Monitoring/Get-PASPSMRecording.ps1, psPAS/Functions/Monitoring/Get-PASPSMSession.ps1, psPAS/Functions/Platforms/Get-PASPlatform.ps1, psPAS/Functions/Safes/Get-PASSafe.ps1, psPAS/Functions/User/Get-PASGroup.ps1, psPAS/Functions/User/Get-PASUser.ps1, psPAS/Private/ConvertTo-QueryString.ps1
Adds `ConvertTo-QueryString`, a new helper function which formats a provided hashtable as query string for use in urls.
Replaces repeated code in various module functions.
Adds logic to only include query in URLs if there is a value assigned to the variable holding the query. Prevents a trailing `?` when no value is present.
All existing pester tests pass.
Invocation of updated functions shows no change in existing module operation
=> URL Helper

README.md, Tests/New-PASPSMSession.Tests.ps1, docs/_data/navigation.yml, docs/collections/_commands/New-PASPSMSession.md, docs/collections/_docs/10-compatibility.md, psPAS/Functions/Connections/New-PASPSMSession.ps1, psPAS/Functions/Platforms/Copy-PASPlatform.ps1, psPAS/Functions/Platforms/Disable-PASPlatform.ps1, psPAS/Functions/Platforms/Enable-PASPlatform.ps1, psPAS/Functions/Platforms/Remove-PASPlatform.ps1, psPAS/Functions/User/Remove-PASGroup.ps1, psPAS/psPAS.psd1
- Renames `Get-PASPSMConnectionParameter` to `New-PASPSMSession`
- Removes Parameter: `connectionParams`
- Adds Parameters: `AllowMappingLocalDrives`, `AllowConnectToConsole`, `RedirectSmartCards`, `PSMRemoteMachine`, `LogonDomain` & `AllowSelectHTML5`
- These are the documented properties expected to be sent as connectionParams.
- This update removes the need from a module user to specify these manually as a hashtable.
Update formats the request as required for both PSMConnect & AdHoc/Secure Connect.
Refactors code for clarity & performance.
Fixes issue where `Path`, if specified, would be inclued in the request body.
Pester Tests updated, request body confirmed as being in expected format.
Test Invocations & Connections successful
Related #263 
Fixes #
Closes #
=> New-PASPSMSession

CHANGELOG.md, README.md, psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/xml/psPAS.CyberArk.Vault.Application.Formats.ps1xml
- Fixes
- Fixes issue where no output would be shown if `filter` parameter was used.
- `Get-PASApplicationAuthenticationMethod`
- Adds properties `Subject`, `Issuer` & `SubjectAlternativeName` to output view.
Expected output returned for the below commands:
- `Get-PASAccount -Safe somesafe`
- `Get-PASAccount -SafeName somesafe`
- `Get-PASAccount -filter 'safeName eq somesafe'`
Expected certificate authentication values shown for the following command:
`Get-PASApplicationAuthenticationMethod -AppID SomeApp`
Fixes #303 
Fixes #304
=> Update Get-PASAccount + Get-PASApplicationAuthenticationMethod

CHANGELOG.md, README.md, Tests/Add-PASOpenIDConnectProvider.Tests.ps1, Tests/Get-PASOpenIDConnectProvider.Tests.ps1, Tests/Remove-PASAuthenticationMethod.Tests.ps1, Tests/Remove-PASOpenIDConnectProvider.Tests.ps1, Tests/Set-PASOpenIDConnectProvider.Tests.ps1, docs/_data/navigation.yml, docs/collections/_commands/Add-PASDiscoveredAccount.md, docs/collections/_commands/Add-PASOpenIDConnectProvider.md, docs/collections/_commands/Get-PASOpenIDConnectProvider.md, docs/collections/_commands/Remove-PASAuthenticationMethod.md, docs/collections/_commands/Remove-PASOpenIDConnectProvider.md, docs/collections/_commands/Set-PASOpenIDConnectProvider.md, docs/collections/_docs/10-compatibility.md, docs/collections/_pages/commands.md, psPAS/Functions/Accounts/Add-PASDiscoveredAccount.ps1, psPAS/Functions/Accounts/Get-PASDiscoveredAccount.ps1, psPAS/Functions/Authentication/Add-PASOpenIDConnectProvider.ps1, psPAS/Functions/Authentication/Get-PASOpenIDConnectProvider.ps1, psPAS/Functions/Authentication/Remove-PASAuthenticationMethod.ps1, psPAS/Functions/Authentication/Remove-PASOpenIDConnectProvider.ps1, psPAS/Functions/Authentication/Set-PASOpenIDConnectProvider.ps1, psPAS/en-US/psPAS-help.xml, psPAS/psPAS.psd1
initial commits of 11.7 features:
- New Functions
- `Add-PASOpenIDConnectProvider`
- Adds a new OIDC authentication provider configuration
- `Get-PASOpenIDConnectProvider`
- Lists configured OIDC authentication providers
- `Set-PASOpenIDConnectProvider`
- Updates a configured OIDC authentication provider
- `Remove-PASOpenIDConnectProvider`
- Deletes a configured OIDC authentication provider
- `Remove-PASAuthenticationMethod`
- Deletes a configured auth method
- `Add-PASDiscoveredAccount`
- Adds support for Azure platform
- `Get-PASDiscoveredAccount`
- Adds support for Azure platform
Pester tests for new functions created, documentation updated.
=> Feature 11.7

Tests/ConvertTo-UnixTime.Tests.ps1, psPAS/Private/ConvertTo-UnixTime.ps1
This PR fixes issue #361, where the ConvertTo-UnixTime function provided invalid values to other functions when the culture is not en-US (or that of the PWV API), which are eventually used by Invoke-PASRestMethod.
Closes #361
=> Resolving issue #361: Added culture awareness to ConvertTo-UnixTime function

CHANGELOG.md, docs/collections/_commands/Set-PASUser.md, psPAS/Functions/User/Set-PASUser.ps1, psPAS/en-US/psPAS-help.xml
`Set-PASUser` no longer set to accept pipeline input for `ExpiryDate` parameter.
DateTime type is expected, but when piping data from `Set-PASUser`, value will be string or unixtime resulting in parameter validation exception.
Fixes #363
=> Fix Set-PASUser Pipeline Operation

CHANGELOG.md, README.md, Tests/ConvertTo-UnixTime.Tests.ps1, docs/collections/_commands/Get-PASAccountPassword.md, docs/collections/_commands/Set-PASUser.md, psPAS/Functions/Accounts/Get-PASAccountPassword.ps1, psPAS/Functions/User/Set-PASUser.ps1, psPAS/Private/ConvertTo-UnixTime.ps1, psPAS/en-US/psPAS-help.xml, psPAS/xml/psPAS.CyberArk.Vault.Credential.Formats.ps1xml, psPAS/xml/psPAS.CyberArk.Vault.Credential.Type.ps1xml
- `ConvertTo-UnixTime`
- Resolves issue where the function provided invalid values when the culture was not 'en-US'.
- `Set-PASUser`
- Sets `ValueFromPipelinebyPropertyName = $false` for `ExpiryDate` parameter, avoids parameter validation exception when piping object representing user, such as the output from `Get-PASUSer`, into `Set-PASUser`.
- `Get-PASAccountPassword`
- MachineName parameter changed to `string` type (previously was incorrectly specified as `switch`)
- Added `UserName` parameter & `ToPsCredential()` Method to enable return of Credential Object.
Closes #363
=> Release 5.1.37

CHANGELOG.md, Tests/Get-PASUser.Tests.ps1, Tests/Remove-PASUser.Tests.ps1, Tests/Set-PASUser.Tests.ps1, Tests/Unblock-PASUser.Tests.ps1, docs/collections/_pages/about.md, psPAS/Functions/Accounts/Add-PASAccount.ps1, psPAS/Functions/Accounts/Set-PASAccount.ps1, psPAS/Functions/User/Get-PASUser.ps1, psPAS/Functions/User/New-PASUser.ps1, psPAS/Functions/User/Remove-PASUser.ps1, psPAS/Functions/User/Set-PASUser.ps1, psPAS/Functions/User/Unblock-PASUser.ps1
- Updates
- Set-PASUser / New-PASUser
- Adds `GUI` as available parameter value for `unAuthorizedInterfaces` parameter.
- Gen1 API Specific
- Add-PASAccount / Set-PASAccount
- Fixes enumeration of dynamic properties for Gen1 requests.
- Reverts Gen1 specific URL update introduced in last release for "_user_" type commands.
- Removes forward slash (/) to end of request URL
- PowerShell version: 7.2.5
- CyberArk PAS version: 11.5 & 12.6
- OS Version:  Win 11
=> 5.3-Update-1

CHANGELOG.md, README.md, Tests/Find-SharedServicesURL.Tests.ps1, Tests/New-PASSession.Tests.ps1, appveyor.yml, build/test.ps1, codecov.yml, docs/collections/_commands/New-PASSession.md, docs/collections/_docs/01-authentication.md, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Private/Find-SharedServicesURL.ps1, psPAS/Private/Get-PASResponse.ps1, psPAS/Private/Invoke-PASRestMethod.ps1, psPAS/en-US/psPAS-help.xml
Abstracts all Privilege Cloud Shared Services authentication operations to the IdentityCommand module.
- Updates & Breaking Change
- `New-PASSession`
- **All Privilege Cloud Shared Services Authentication via the CyberArk Identity Platform now requires use of the pspete `IdentityCommand` module.**
- Adds Identity User Authentication, using the `IdentityCommand` module to satisfy Identity MFA challenges and obtain required authentication token to use against Privileged Cloud Shared Services.
- Adds logic to determine correct Identity tenant URL based on provided Privileged Cloud Subdomain value.
- Both Privileged Cloud API URL & Identity Portal URL are required to be specified if subdomain value is not provided.
Required Parameter changes in New-PASSession make this a breaking change for …
=> ADD Dependancy on IdentityCommand module 

Tests/Get-PASServerWebService.Tests.ps1, docs/collections/_commands/Add-PASPendingAccount.md, docs/collections/_commands/Get-PASAccountActivity.md, docs/collections/_commands/Get-PASSafeShareLogo.md, docs/collections/_commands/Get-PASServerWebService.md, docs/collections/_commands/Invoke-PASCPMOperation.md, psPAS/Functions/Accounts/Add-PASPendingAccount.ps1, psPAS/Functions/Accounts/Get-PASAccountActivity.ps1, psPAS/Functions/Accounts/Invoke-PASCPMOperation.ps1, psPAS/Functions/ServerWebServices/Get-PASSafeShareLogo.ps1, psPAS/Functions/ServerWebServices/Get-PASServerWebService.ps1, psPAS/en-US/psPAS-help.xml
Following the product release notes, adds 13.2 as the maximum supported version for commands or paramters/parametersets scheduled for depreciation:
- `Get-PASServerWebService` (Gen1)
- `Get-PASSafeShareLogo`
- `Invoke-PASCPMOperation` (Gen1)
- `Get-PASAccountActivity`
- `Add-PASPendingAccount`
Fixes #
- OS Version: Win11
=> Depreciate Commands

CHANGELOG.md, Tests/Get-NextLink.Tests.ps1, Tests/Get-PASServerWebService.Tests.ps1, docs/collections/_commands/Add-PASPendingAccount.md, docs/collections/_commands/Get-PASAccountActivity.md, docs/collections/_commands/Get-PASSafeShareLogo.md, docs/collections/_commands/Get-PASServerWebService.md, docs/collections/_commands/Invoke-PASCPMOperation.md, docs/collections/_commands/Set-PASSafe.md, docs/collections/_posts/2023-09-06-pspas-release-6-0.md, psPAS/Functions/Accounts/Add-PASPendingAccount.ps1, psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/Functions/Accounts/Get-PASAccountActivity.ps1, psPAS/Functions/Accounts/Invoke-PASCPMOperation.ps1, psPAS/Functions/Safes/Set-PASSafe.ps1, psPAS/Functions/ServerWebServices/Get-PASSafeShareLogo.ps1, psPAS/Functions/ServerWebServices/Get-PASServerWebService.ps1, psPAS/Private/Get-NextLink.ps1, psPAS/en-US/psPAS-help.xml
- `Set-PASSafe`
- Allows `0` as valid value for parameter `NumberOfDaysRetention`
- `Get-PASServerWebService`
- Depreciates Gen1 endpoint from 13.2. Adds Gen2 endpoint as default.
- `Get-PASSafeShareLogo`
- Depreciates command from 13.2.
- `Invoke-PASCPMOperation`
- Depreciates Gen1 endpoint from 13.2.
- `Get-PASAccountActivity`
- Depreciates command from 13.2.
- `Add-PASPendingAccount`
- Depreciates command from 13.2.
- Resolves issue where, if number of results of a `SavedFilter` are greater than the page size (either default or set via the `limit` parameter), only the URL of the first request sent would include the SavedFilter value.
- 
Fixes #493 
Fixes #491
=> 6.0 Update 2

CHANGELOG.md, psPAS/Functions/Applications/Add-PASApplication.ps1
Updates date format of `ExpirationDate` to `MM/dd/yyyy`. Resolves issue observed when sending date format of `MM-dd-yyyy`
Fixes #501 
- OS Version: Win11
=> FIX invalid parameter expirationdate when adding application

CHANGELOG.md, Tests/Get-PASPSMRecording.Tests.ps1, Tests/Get-PASPSMSession.Tests.ps1, Tests/Get-PASSession.Tests.ps1, Tests/Invoke-PASRestMethod.Tests.ps1, docs/collections/_commands/Get-PASAccount.md, docs/collections/_commands/Get-PASDiscoveredAccount.md, docs/collections/_commands/Get-PASPSMRecording.md, docs/collections/_commands/Get-PASPSMSession.md, docs/collections/_commands/Get-PASPlatform.md, docs/collections/_commands/Get-PASSession.md, docs/collections/_posts/2024-02-01-pspas-release-6-1.md, psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/Functions/Accounts/Get-PASDiscoveredAccount.ps1, psPAS/Functions/Authentication/Get-PASSession.ps1, psPAS/Functions/Monitoring/Get-PASPSMRecording.ps1, psPAS/Functions/Monitoring/Get-PASPSMSession.ps1, psPAS/Functions/Platforms/Get-PASPlatform.ps1, psPAS/Private/Invoke-PASRestMethod.ps1, psPAS/en-US/psPAS-help.xml
- N/A
- `Get-PASPSMRecording`
- Removes `Offset` Parameter
- Updates `FromTime` & `ToTime` parameters to `[datetime]` types
- Returns all pages of results instead of only the first page of results
- `Get-PASPSMSession`
- Removes `Offset` Parameter
- Updates `FromTime` & `ToTime` parameters to `[datetime]` types
- Returns all pages of results instead of only the first page of results
- Removes `Offset` Parameter
- `Get-PASDiscoveredAccount`
- Removes `Offset` Parameter
- `Get-PASSession`
- Removes `UserName` from command output, avoiding error condition on expired session.
- `Get-PASPlatform`
- Adds `search` parameter to the default `targets` parameterset
- ISPSS Error Handling
- Fixes issue where error returned from ISPSS solution may not be handled properly
Fixes #522 …
=> 6.1 Update 1

psPAS/Functions/SafeMembers/Set-PASSafeMember.ps1
I've encountered the same issue as #561. It appears that with at least 14.2, the membershipExpireDate parameter must be supplied on all safe member updates. The Set-PASSafeMember function works if we pass it a date value. However, if you don't actually want a date assigned, you need submit null. This pull request allows use of $null.
Fixes #561 
Example of not providing parameter:
```
Set-PASSafeMember -SafeName TEST-EXPIRE -MemberName "testuser" -AddAccounts $true
Invoke-PASRestMethod : [400] There are some invalid parameters
ErrorCode=PASWS178E; ErrorMessage=Parameter [MembershipExpirationDate] must be between [0] and [2145830400]; ParameterName=MembershipExpirationDate
At line:551 char:14
+ ...      $result = Invoke-PASRestMethod -Uri $URI -Method PUT -Body $Body
+ …
```
=> Allow membershipExpirationDate value to be null.
