CONTRIBUTING.md, Functions/Authentication/Close-PASSAMLSession.ps1, Functions/Authentication/Close-PASSharedSession.ps1, Functions/Authentication/New-PASSAMLSession.ps1, Functions/Authentication/New-PASSharedSession.ps1, README.md, psPAS.psd1
Add functions for Shared Logon/Logoff
:small_red_triangle_down: Add (broken) functions for SAML Logon/Logoff.
Update README.md
Update CONTRIBUTING.md
=> Add Authentication Functions

Private/Get-EscapedString.ps1
Update typo in Help Text of Get-EscapedString
Resolves issue #8
=> Update Help Text

Private/Invoke-PASRestMethod.ps1, README.md
Update Invoke-PASRestMethod to set Security Protocol to TLS 1.2 if it is
available and not already being used.
Resolves #11
=> Add TLS1.2 Enforcement

Functions/SafeMembers/Get-PASSafeMembers.ps1, Functions/SafeMembers/Set-PASSafeMember.ps1, README.md
Minor fixes and enhancements to output of Get-PASSafeMember and
Set-PASSafeMember
=> Fix-Safe-Members

Functions/SafeMembers/Add-PASSafeMember.ps1, Functions/SafeMembers/Set-PASSafeMember.ps1
Set-PASSafeMember & Add-PASSafeMember were missing the RenameAccounts Parameter.
Now added.
Resolves #20
=> ADD RenameAccounts Parameter

Private/Invoke-PASRestMethod.ps1, README.md, psPAS.psd1
On error, the native error message recieved from the webservice is included, with the status code, in the error message.
The native CyberArk error code is added to the error record and included in the FullyQualifiedErrorId.
=> UPDATE Error Output

Functions/AccountACL/Add-PASAccountACL.ps1, Functions/AccountACL/Get-PASAccountACL.ps1, Functions/AccountGroups/Add-PASAccountGroupMember.ps1, Functions/Accounts/Get-PASAccount.ps1, Functions/Accounts/Get-PASAccountActivity.ps1, Functions/Accounts/Get-PASAccountPassword.ps1, Functions/Applications/Get-PASApplication.ps1, Functions/Applications/Get-PASApplicationAuthenticationMethod.ps1, Functions/Authentication/Add-PASPublicSSHKey.ps1, Functions/Authentication/Get-PASPublicSSHKey.ps1, Functions/OnboardingRules/Get-PASOnboardingRule.ps1, Functions/PolicyACL/Add-PASPolicyACL.ps1, Functions/PolicyACL/Get-PASPolicyACL.ps1, Functions/SafeMembers/Add-PASSafeMember.ps1, Functions/SafeMembers/Get-PASSafeMember.ps1, Functions/Safes/Add-PASSafe.ps1, Functions/Safes/Get-PASSafe.ps1, Functions/ServerWebServices/Get-PASSafeShareLogo.ps1, Functions/ServerWebServices/Get-PASServer.ps1, Functions/ServerWebServices/Get-PASServerWebService.ps1, Functions/User/Add-PASGroupMember.ps1, Functions/User/Get-PASLoggedOnUser.ps1, Functions/User/Get-PASUser.ps1, Functions/User/Unblock-PASUser.ps1, README.md, psPAS.psd1
Moved function output from the END block to the PROCESS block.
When multiple objects are piped into the function, ensures all results, and not just the last result, are returned to the pipeline.
=> Rework Output

Functions/AccountACL/Add-PASAccountACL.ps1, Functions/AccountGroups/Add-PASAccountGroupMember.ps1, Functions/AccountGroups/New-PASAccountGroup.ps1, Functions/Accounts/Add-PASAccount.ps1, Functions/Accounts/Add-PASPendingAccount.ps1, Functions/Accounts/Get-PASAccount.ps1, Functions/Accounts/Set-PASAccount.ps1, Functions/Accounts/Start-PASCredChange.ps1, Functions/Applications/Add-PASApplication.ps1, Functions/Applications/Add-PASApplicationAuthenticationMethod.ps1, Functions/Applications/Get-PASApplication.ps1, Functions/Authentication/New-PASSession.ps1, Functions/OnboardingRules/New-PASOnboardingRule.ps1, Functions/PolicyACL/Add-PASPolicyACL.ps1, Functions/SafeMembers/Add-PASSafeMember.ps1, Functions/SafeMembers/Set-PASSafeMember.ps1, Functions/Safes/Add-PASSafe.ps1, Functions/Safes/Get-PASSafe.ps1, Functions/Safes/Set-PASSafe.ps1, Functions/User/Add-PASGroupMember.ps1, Functions/User/New-PASUser.ps1, Functions/User/Set-PASUser.ps1, Functions/User/Unblock-PASUser.ps1, README.md, psPAS.psd1
All references to "Get-PASParameters" (Private Function) have been replaced with "Get-PASParameter" after feedback received relating to an introduced functional issue.
Resolves #34
=> FIX Function Call

README.md
Using http://doctoc.herokuapp.com - I generated a Table of Contents and verified all links are working correctly to jump to each section.
=> Fix #41 - Add Table of Contents to README.md

Functions/Authentication/New-PASSAMLSession.ps1, Functions/Authentication/New-PASSession.ps1, Functions/Authentication/New-PASSharedSession.ps1
Create $SessionToken as explicit string in Authentication functions.
Resolves #43
=> Issue 43 - FIX WMF3 Compatibility

Functions/Accounts/Add-PASPendingAccount.ps1, Functions/Accounts/Start-PASCredChange.ps1, Functions/SafeMembers/Add-PASSafeMember.ps1, Functions/SafeMembers/Set-PASSafeMember.ps1, Private/New-DynamicParam.ps1, psPAS.psd1
Some PSScriptAnalyzer rules suppressed as they were generating false
positive Errors or Warnings. Mainly due to parameter names
("username"/"password"/"creds"), which cannot be changed due to the
recieving API.
This PR fixes/implements the following:
When running PSScriptAnalyzer, prevents the following functions generating the below findings:
**Add-PASPendingAccount**/_PSAvoidUsingUserNameAndPassWordParams_
**Add-PASPendingAccount**/_PSAvoidUsingPlainTextForPassword_
**New-DynamicParam**/_PSUseShouldProcessForStateChangingFunctions_
**Set-PASSafeMember**/_PSUseDeclaredVarsMoreThanAssignments_
**Add-PASSafeMember**/_PSUseDeclaredVarsMoreThanAssignments_
**Start-PASCredChange**/_PSAvoidUsingPlainTextForPassword_
_Explain the **motivation** for making this change. What existing problem does …
=> ADD SuppressMessageAttribute

Tests/New-PASSession.Tests.ps1, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Private/Get-PASParameter.ps1
Minor fixes relating to commits made for #70
=> Issue 70-Fix

psPAS/Private/Invoke-PASRestMethod.ps1
This PR fixes/implements the following #131
_Explain the **motivation** for making this change. What existing problem does the pull request solve?_
Remove a write-debug that prints user's credentials
Fixes #131 
Closes #131
=> :lock: Do not print out credentials

CHANGELOG.md, README.md, Tests/Add-PASDirectory.Tests.ps1, Tests/Get-PASDirectory.Tests.ps1, Tests/Get-PASDirectoryMapping.Tests.ps1, Tests/New-PASDirectoryMapping.Tests.ps1, Tests/Remove-PASDirectory.Tests.ps1, Tests/Set-PASDirectoryMapping.Tests.ps1, Tests/Set-PASSafe.Tests.ps1, appveyor.yml, psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/Functions/LDAPDirectories/Add-PASDirectory.ps1, psPAS/Functions/LDAPDirectories/Get-PASDirectory.ps1, psPAS/Functions/LDAPDirectories/Get-PASDirectoryMapping.ps1, psPAS/Functions/LDAPDirectories/New-PASDirectoryMapping.ps1, psPAS/Functions/LDAPDirectories/Remove-PASDirectory.ps1, psPAS/Functions/LDAPDirectories/Set-PASDirectoryMapping.ps1, psPAS/Functions/Requests/Approve-PASRequest.ps1, psPAS/Functions/Requests/Deny-PASRequest.ps1, psPAS/Functions/Requests/Get-PASRequest.ps1, psPAS/Functions/Requests/Get-PASRequestDetail.ps1, psPAS/Functions/Requests/New-PASRequest.ps1, psPAS/Functions/Requests/Remove-PASRequest.ps1, psPAS/Functions/Safes/Set-PASSafe.ps1, psPAS/psPAS.CyberArk.Vault.Directory.Formats.ps1xml, psPAS/psPAS.psd1
Updates module for PAS 10.7
This PR fixes/implements the following **bugs/features**:
- New Functions
- `Get-PASDirectoryMapping`
- Get directory mappings configured for a directory
- `Get-PASDirectoryMapping`
- Adds a new Directory Mapping for an existing directory
- `Remove-PASDirectory`
- Removes a directory configured in the Vault
- `Add-PASDirectory`
- Added parameter `DCList`
- `Get-PASDirectory`
- Function output updated to contain more properties
- `New-PASDirectoryMapping`
- Added parameters `VaultGroups`, `Location`, `LDAPQuery`
- `Set-PASSafe`
- Now supports renaming a safe via `NewSafeName` parameter
- Other Updates
- Updated comment based help content based on user feedback.
Pester tests updated
Fixes #
Closes #138
=> Feature 10.7

CHANGELOG.md, README.md, Tests/Get-PASUser.Tests.ps1, Tests/New-PASUser.Tests.ps1, appveyor.yml, psPAS/Functions/Accounts/Add-PASAccount.ps1, psPAS/Functions/User/Get-PASUser.ps1, psPAS/Functions/User/New-PASUser.ps1, psPAS/Private/Get-PASParameter.ps1, psPAS/psPAS.CyberArk.Vault.User.Formats.ps1xml
- `New-PASUser`
- Added support for the updated Add User API method for v10.9
- `Get-PASUser`
- Added support for the updated Get Users API method for v10.9
=> Feature 10 9

build/test.ps1, psPAS/Functions/Accounts/Add-PASDiscoveredAccount.ps1, psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/Functions/Accounts/Invoke-PASCredChange.ps1, psPAS/Functions/Accounts/Set-PASAccount.ps1, psPAS/Functions/LDAPDirectories/Add-PASDirectory.ps1, psPAS/Functions/Monitoring/Connect-PASPSMSession.ps1, psPAS/Functions/OnboardingRules/Get-PASOnboardingRule.ps1, psPAS/Private/Compare-MinimumVersion.ps1, psPAS/Private/Get-PASParameter.ps1, psPAS/Private/Invoke-PASRestMethod.ps1, psPAS/psPAS.psm1
:mute: Removing all output to verbose & debug message streams.
=> REMOVE Verbose & Debug Output

psPAS/Functions/Safes/Find-PASSafe.ps1
This PR fixes/implements the following features:  New function to invoke the /api/Safes endpoint entitled Find-PASSafe, based on [List Safes](https://cyberarkdocu.azurewebsites.net/Product-Doc/OnlineHelp/PAS/Latest/en/Content/SDK/Safes%20Web%20Services%20-%20List%20Safes.htm) (list is not a PS Verb)
This v10 endpoint performs faster than the v9 endpoint.  It also returns fewer details about the safes returned.
$Token | Find-PASSafe
$Token | Find-PASSafe -search "sredden"
$Token | Find-PASSafe -search "sredden safe2"
N/A
=> init Find-PASSafe

CHANGELOG.md, README.md, Tests/Find-PASSafe.Tests.ps1, psPAS/Functions/Safes/Find-PASSafe.ps1, psPAS/psPAS.psd1
Adding support for contribution from [steveredden](https://github.com/steveredden).
- ➕ `Find-PASSafe`
- Added version check - set to require 10.1 minimum (:question:)
- Added Pester Tests for code coverage :100:
- Updated Readme & Changelog
- Added to exported functions
=> ADD Find-PASSafe

Tests/Get-PASResponse.Tests.ps1, Tests/Invoke-PASRestMethod.Tests.ps1, psPAS/Private/Get-PASResponse.ps1, psPAS/Private/Invoke-PASRestMethod.ps1
🆕  `Get-PASResponse` - added helper function to deal with `Invoke-WebRequest` output.
♻️ `Invoke-PASRestMethod` - removed parsing of `Invoke-WebRequest` output, improved exception handling.
✅ `Invoke-PASRestMethod.Tests` - rewrote tests covering all functionality & error scenarios.
=> Update request response

Tests/Invoke-PASRestMethod.Tests.ps1, psPAS/Functions/Authentication/Close-PASSession.ps1, psPAS/Private/Invoke-PASRestMethod.ps1
Check for `[System.Net.Http.HttpRequestException]` only works for PSCore. `Invoke-WebRequest` in Powershell 5 raises a `[Net.WebException]`.
`Invoke-PASRequest` updated to handle both PSCore & PowerShell scenarios.
=> Exceptions

CHANGELOG.md, README.md, Tests/Get-PASUser.Tests.ps1, Tests/New-PASDirectoryMapping.Tests.ps1, Tests/Set-PASDirectoryMapping.Tests.ps1, Tests/Set-PASDirectoryMappingOrder.Tests.ps1, Tests/Set-PASUserPassword.Tests.ps1, Tests/Unblock-PASUser.Tests.ps1, psPAS/Functions/LDAPDirectories/New-PASDirectoryMapping.ps1, psPAS/Functions/LDAPDirectories/Set-PASDirectoryMapping.ps1, psPAS/Functions/LDAPDirectories/Set-PASDirectoryMappingOrder.ps1, psPAS/Functions/User/Get-PASUser.ps1, psPAS/Functions/User/Set-PASUserPassword.ps1, psPAS/Functions/User/Unblock-PASUser.ps1, psPAS/psPAS.psd1
- New Functions
- `Set-PASUserPassword`
- Reset user passwords
- `Set-PASDirectoryMappingOrder`
- Reorder directory mappings
- `New-PASDirectoryMapping`
- Added parameter `UserActivityLogPeriod` for 10.10 API
- `Set-PASDirectoryMapping`
- Added parameter `UserActivityLogPeriod` for 10.10 API
- `Get-PASUser`
- Added parameter `id` for 10.10 API
- `Unblock-PASUser`
- Added parameter `id` for 10.10 API endpoint
=> v10.10 Update

Tests/Get-PASUser.Tests.ps1
=> FIX Get-PASUser.Tests

CHANGELOG.md, README.md, Tests/Get-PASUser.Tests.ps1, Tests/New-PASDirectoryMapping.Tests.ps1, Tests/Set-PASDirectoryMapping.Tests.ps1, Tests/Set-PASDirectoryMappingOrder.Tests.ps1, Tests/Set-PASUserPassword.Tests.ps1, appveyor.yml, psPAS/Functions/LDAPDirectories/New-PASDirectoryMapping.ps1, psPAS/Functions/LDAPDirectories/Set-PASDirectoryMapping.ps1, psPAS/Functions/LDAPDirectories/Set-PASDirectoryMappingOrder.ps1, psPAS/Functions/User/Get-PASUser.ps1, psPAS/Functions/User/Set-PASUserPassword.ps1, psPAS/Functions/User/Unblock-PASUser.ps1, psPAS/psPAS.psd1
- New Functions
- `Set-PASUserPassword`
- Reset user passwords
- `Set-PASDirectoryMappingOrder`
- Reorder directory mappings
- `New-PASDirectoryMapping`
- Added parameter `UserActivityLogPeriod` for 10.10 API
- `Set-PASDirectoryMapping`
- Added parameter `UserActivityLogPeriod` for 10.10 API
- `Get-PASUser`
- Added parameter `id` for 10.10 API
- `Unblock-PASUser`
- Added parameter `id` for 10.10 API endpoint
=> v10.10 Features

README.md, Tests/New-PASDirectoryMapping.Tests.ps1, Tests/New-PASGroup.Tests.ps1, Tests/Remove-PASUser.Tests.ps1, Tests/Set-PASUser.Tests.ps1, psPAS/Functions/User/New-PASGroup.ps1, psPAS/Functions/User/Remove-PASUser.ps1, psPAS/Functions/User/Set-PASUser.ps1, psPAS/psPAS.psd1
Adds:
Create Group
Update User
Delete User
=> 11.1 user functions

Tests/Get-PASPlatform.Tests.ps1, Tests/Get-PASPlatformSafe.Tests.ps1, psPAS/Functions/Platforms/Get-PASPlatform.ps1, psPAS/Functions/Platforms/Get-PASPlatformSafe.ps1, psPAS/psPAS.psd1
platform function updates for 11.1
=> 11.1 platforms functions

CHANGELOG.md, psPAS/Private/Invoke-PASRestMethod.ps1
Added more verbose error messages.
_Explain the **motivation** for making this change. What existing problem does the pull request solve?_
Adding capability to provide more detail in error messages.
Some exceptions contain an inner error object with additional error information.
Adding this detail to the error message along with error codes.
_Demonstrate the code is solid. Example: The exact commands you ran and their output._
Fixes #
Closes #
=> Update Error Messages

CHANGELOG.md, build/deploy.ps1, docs/collections/_commands/Add-PASDiscoveredAccount.md, docs/collections/_commands/Disable-PASCPMAutoManagement.md, docs/collections/_commands/Enable-PASCPMAutoManagement.md, docs/collections/_commands/Get-PASPlatform.md, docs/collections/_commands/Get-PASPlatformSafe.md, docs/collections/_commands/New-PASGroup.md, docs/collections/_commands/New-PASSession.md, docs/collections/_commands/Remove-PASDirectoryMapping.md, docs/collections/_commands/Remove-PASUser.md, docs/collections/_commands/Set-PASDirectoryMapping.md, docs/collections/_commands/Set-PASUser.md
Build to deploy new module version to PowerShell Gallery
=> Deploy 3.3

README.md, Tests/Test-PASPSMRecording.Tests.ps1, docs/_data/navigation.yml, docs/collections/_commands/Test-PASPSMRecording.md, docs/collections/_docs/10-compatibility.md, docs/collections/_pages/about.md, psPAS/Functions/Monitoring/Test-PASPSMRecording.ps1, psPAS/psPAS.psd1
=> Feature 11 2

README.md, Tests/New-PASSession.Tests.ps1, docs/collections/_commands/Get-PASAccount.md, docs/collections/_commands/New-PASSession.md, docs/collections/_docs/10-compatibility.md, psPAS/Functions/Authentication/New-PASSession.ps1
Update for capability introduced in 11.3.
Adds `concurrentSession` parameter to `New-PASSession`.
=> Feature: 11.3

Tests/ConvertTo-UnixTime.Tests.ps1, Tests/Get-PASAccount.Tests.ps1, Tests/psPAS.Tests.ps1, psPAS/Functions/Accounts/Remove-PASAccount.ps1, psPAS/Functions/Authentication/Close-PASSession.ps1, psPAS/Functions/Platforms/Disable-PASPlatform.ps1, psPAS/Functions/Platforms/Enable-PASPlatform.ps1, psPAS/Functions/Platforms/Remove-PASPlatform.ps1, psPAS/Functions/ServerWebServices/Get-PASServerWebService.ps1, psPAS/Private/ConvertTo-InsecureString.ps1, psPAS/Private/ConvertTo-QueryString.ps1, psPAS/Private/ConvertTo-UnixTime.ps1, psPAS/Private/Get-PASParameter.ps1, psPAS/Private/Get-PASSAMLResponse.ps1, psPAS/Private/Get-ParentFunction.ps1
Reinstates module consistency checks which have now been refactored to work with Pester 5.
PR includes fixes to failed tests & PSScriptAnalyzer findings which were previously missed due to the tests not running.
=> Module Pester Tests

CHANGELOG.md, Tests/New-PASSession.Tests.ps1, Tests/Remove-PASAccountACL.Tests.ps1, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Private/Get-PASSAMLResponse.ps1, psPAS/Private/Invoke-PASRestMethod.ps1
This PR fixes **Gen2 SAML Authentication**:
- Code logic to get SAML Response via SSO using default credentials updated to correct format of authentication request.
- Option added for user to provide their own SAMLResponse as string value.
Tested & validated SAML SSO against ADFS 2019
Fixes #
Closes #
=> Gen2 SAML Authentication

CHANGELOG.md, Tests/Get-PASSession.Tests.ps1, Tests/Remove-PASGroupMember.Tests.ps1, docs/collections/_commands/Add-PASSafeMember.md, psPAS/Functions/Authentication/Get-PASSession.ps1, psPAS/Functions/Platforms/Get-PASPlatform.ps1, psPAS/Functions/SafeMembers/Add-PASSafeMember.ps1, psPAS/Functions/User/Remove-PASGroupMember.ps1, psPAS/en-US/psPAS-help.xml
- Updates
- `Get-PASSession`
- Catch errors getting the username of the logged on user so session token and other information can still be extracted from the module scope.
- `Add-PASSafeMember`
- Makes `InitiateCPMAccountManagementOperations` non-mandatory; fixes issue introduced in `5.1.16`.
- `Remove-PASGroupMember`
- Resolves issue where attempting to remove group member with an '@' symbol in the user name reported a 404 error.
- `Get-PASPlatform`
- Fixes issue where expected output was not displayed when using the `platforms` parameterset.
Resolves #356 
Resolves #359 
Fix #355 
Fix #349
=> Release Minor Fixes

.gitignore, CHANGELOG.md, README.md, Tests/Get-PASAccountDetail.Tests.ps1, Tests/Request-PASJustInTimeAccess.Tests.ps1, Tests/Revoke-PASJustInTimeAccess.Tests.ps1, docs/_data/navigation.yml, docs/collections/_commands/Get-PASAccountDetail.md, docs/collections/_commands/Request-PASJustInTimeAccess.md, docs/collections/_commands/Revoke-PASJustInTimeAccess.md, docs/collections/_docs/10-compatibility.md, docs/collections/_pages/commands.md, psPAS/Functions/Accounts/Get-PASAccountDetail.ps1, psPAS/Functions/Accounts/Request-PASJustInTimeAccess.ps1, psPAS/Functions/Accounts/Revoke-PASJustInTimeAccess.ps1, psPAS/Functions/Connections/New-PASPSMSession.ps1, psPAS/en-US/psPAS-help.xml, psPAS/psPAS.psd1, psPAS/xml/psPAS.CyberArk.Vault.Account.Type.ps1xml
Add latest updates to dev branch
=> Version update

CHANGELOG.md, psPAS/psPAS.psd1
- Fix
- Added `Request-PASJustInTimeAccess` as Exported Function in `psPAS.psd1`.
Fixes #379 
- PowerShell version:
- CyberArk PAS version:
- OS Version:
=> Fix Previous Release

CHANGELOG.md, Tests/Disable-PASUser.Tests.ps1, Tests/Enable-PASUser.Tests.ps1, Tests/Get-PASAccountGroup.Tests.ps1, Tests/Get-PASGroup.Tests.ps1, docs/collections/_commands/Disable-PASUser.md, docs/collections/_commands/Enable-PASUser.md, docs/collections/_commands/Get-PASAccount.md, docs/collections/_commands/Get-PASAccountGroup.md, docs/collections/_commands/Get-PASGroup.md, docs/collections/_commands/Get-PASUser.md, docs/collections/_commands/Set-PASSafe.md, psPAS/Functions/AccountGroups/Get-PASAccountGroup.ps1, psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/Functions/User/Disable-PASUser.ps1, psPAS/Functions/User/Enable-PASUser.ps1, psPAS/Functions/User/Get-PASGroup.ps1, psPAS/en-US/psPAS-help.xml, psPAS/psPAS.psd1
Updates and additions related to updates contained in CyberArk 12.6
- New Commands
- `Enable-PASUser`
- New command, supported from 12.6
- `Disable-PASUser`
- New command, supported from 12.6
- Updates
- Added `savedFilter` parameter, supported from 12.6
- `Get-PASGroup`
- Added `id` parameter, supported from 12.6
- `Get-PASAccountGroup`
- Depreciated use of "Get Safe account groups" API
- Makes ParameterSet based on `Get account group by Safe` API the default.
- Updated documentation and help text.
Fixes #
- PowerShell version: 7.2.5
- CyberArk PAS version: 12.6
=> Feature additions 12.6

Tests/Get-PASUser.Tests.ps1, Tests/Remove-PASUser.Tests.ps1, Tests/Set-PASUser.Tests.ps1, Tests/Unblock-PASUser.Tests.ps1, psPAS/Functions/Accounts/Add-PASAccount.ps1, psPAS/Functions/Accounts/Set-PASAccount.ps1, psPAS/Functions/User/Get-PASUser.ps1, psPAS/Functions/User/New-PASUser.ps1, psPAS/Functions/User/Remove-PASUser.ps1, psPAS/Functions/User/Set-PASUser.ps1, psPAS/Functions/User/Unblock-PASUser.ps1
- Reverts URL formatting to remove forward slash (/) in Gen1 URL introduced in last release.
- Fixes dynamic property enumeration when adding or updating accounts using Gen1 API
- Adds "GUI" in ValidateSet for `unAuthorizedInterfaces` parameter when creating or updating users
Fixes #405
Fixes #407
Fixes #409 
- PowerShell version: 7.2.5
- CyberArk PAS version: 12.6 & 11.5
=> Issues 405, 407, 409

docs/collections/_commands/New-PASSession.md, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/en-US/psPAS-help.xml
Adds PKI authentication type option.
Allows user to perform primary authentication using  certificate/smartcard, and secondary authentication using LDAP credentials. Requested under #404
Fixes #
- PowerShell version: 5.1 & 7.2.6
- CyberArk PAS version: 12.6
=> Feature: PKI Authentication

docs/collections/_commands/Get-PASAccount.md, psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/en-US/psPAS-help.xml
Reinstates `limit` & `offset` parameters which were previously removed. 
Allows users to specify their own page size values for returned results.
Fixes #
- CyberArk PAS version: 12.6
- OS Version: Win11
=> 🚸⏪️UPDATE Get-PASAccount

docs/collections/_commands/Add-PASAccount.md
Fixes #
- [ X] Documentation update (psPAS website or command help content)
- PowerShell version:
- CyberArk PAS version:
- OS Version:
- [ x] I have followed the contributing guidelines.
- [ x] My changes generate no new test failures or errors
=> add an extra example to Add-PASAccount to showcase how to add a account that uses ssh certificates. 

CHANGELOG.md, Tests/Get-PASSafeMember.Tests.ps1, docs/collections/_commands/Add-PASAccount.md, docs/collections/_commands/Add-PASPersonalAdminAccount.md, docs/collections/_commands/Get-PASAccount.md, docs/collections/_commands/New-PASAccountObject.md, docs/collections/_commands/New-PASSession.md, docs/collections/_commands/Set-PASPTARule.md, docs/collections/_posts/2022-09-26-pspas-release-5-4.md, docs/package-lock.json, psPAS/Functions/EventSecurity/Set-PASPTARule.ps1, psPAS/Functions/SafeMembers/Get-PASSafeMember.ps1, psPAS/en-US/psPAS-help.xml
- Fix `Get-PASSafeMember`
- Corrects format of URL value when returning many safe members
- Thanks [InconstantRO](https://github.com/InconstantRO)!
- Documentation
- Additional example added to `Get-PASAccount` help file
- Thanks [rorobig](https://github.com/rorobig)!
Fixes #433
- PowerShell version: 7.3.0
- CyberArk PAS version: 12.6
=> 5.4-Update-1 

CHANGELOG.md, README.md, Tests/New-PASSession.Tests.ps1, docs/collections/_commands/New-PASSession.md, docs/collections/_docs/01-authentication.md, docs/collections/_posts/2023-03-06-pspas-release-5-6.md, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/en-US/psPAS-help.xml
Adds PKIPN authentication option to `New-PASSession`
Fixes #463
=> PKIPN Authentication

CHANGELOG.md, Tests/New-PASSession.Tests.ps1, docs/collections/_commands/New-PASSession.md, docs/collections/_docs/01-authentication.md, docs/collections/_posts/2023-03-06-pspas-release-5-6.md, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/en-US/psPAS-help.xml
Updates Shared Services (ISPSS) authentication options.
- allows different subdomains for identity/P Cloud to be specified
- allows tenant URLs for Identity/P Cloud to be specified
Fixes #472
Fixes #465
- PowerShell version: 7 
=> UPDATE ISPSS Authentication

README.md
=> Fixes "List of Functions" links in README.md file

CHANGELOG.md, docs/collections/_commands/Add-PASSafeMember.md, psPAS/Functions/SafeMembers/Add-PASSafeMember.ps1, psPAS/en-US/psPAS-help.xml
Adds 'Role' to acceptable values in ParameterSet for `memberType` parameter.
Fixes #487 
- PowerShell version:
- CyberArk PAS version:
- OS Version:
=> 6.0 Update 1

CHANGELOG.md, docs/collections/_posts/2023-03-06-pspas-release-5-5.md, docs/collections/_posts/2023-09-06-pspas-release-6-0.md, psPAS/Functions/Authentication/New-PASSession.ps1, psPAS/Private/Hide-SecretValue.ps1, psPAS/Private/Send-RADIUSResponse.ps1
Resolves condition where authentication password value might be revealed in debug trace output in a scenario where  `Set-PSDebug -Trace 2` is active in the console host.
Fixes #
=>  6.0 Update 3

CHANGELOG.md, Tests/Add-PASPTARule.Tests.ps1, Tests/Set-PASPTARemediation.Tests.ps1, Tests/Set-PASPTARule.Tests.ps1, docs/collections/_commands/Add-PASPTARule.md, docs/collections/_commands/Set-PASPTARule.md, psPAS/Functions/EventSecurity/Add-PASPTARule.ps1, psPAS/Functions/EventSecurity/Set-PASPTAEvent.ps1, psPAS/Functions/EventSecurity/Set-PASPTARemediation.ps1, psPAS/Functions/EventSecurity/Set-PASPTARiskEvent.ps1, psPAS/Functions/EventSecurity/Set-PASPTARule.ps1, psPAS/en-US/psPAS-help.xml, psPAS/xml/psPAS.CyberArk.Vault.PTA.Formats.ps1xml
- Fixes `Set-PASPTAEvent` & `Set-PASPTARiskEvent`
- Fixes issue where websession object and auth header were not being sent with the request
- Updates `Add-PASPTARule` & `Set-PASPTARule`
- Adds scope parameters `vaultUsersMode`, `vaultUsersList`, `machinesMode` & `machinesList`
- Includes scope property in output by default
Fixes #
- OS Version: Win11
=> PTA Update

psPAS/Private/Invoke-PASRestMethod.ps1
Avoids potential error condition when handling errors in ISPSS environments 
Fixes #
- CyberArk PAS version: 14.0
=> ISPSS Error Experiment

CHANGELOG.md, README.md, Tests/Get-PASLinkedGroup.Tests.ps1, docs/collections/_commands/Get-PASLinkedGroup.md, docs/collections/_docs/10-compatibility.md, psPAS/Functions/Accounts/Get-PASLinkedGroup.ps1, psPAS/en-US/psPAS-help.xml, psPAS/psPAS.psd1
Adds `Get-PASLinkedGroup` to get linked account groups of an account
Closes #508
- CyberArk PAS version: 14
- OS Version: 11
=> ⚗️ADD Get-PASLinkedGroup

CHANGELOG.md, docs/collections/_posts/2024-02-01-pspas-release-6-1.md
=> Version Bump

CHANGELOG.md, Tests/Get-PASPSMRecording.Tests.ps1, Tests/Get-PASPSMSession.Tests.ps1, Tests/Get-PASSession.Tests.ps1, Tests/Invoke-PASRestMethod.Tests.ps1, docs/collections/_commands/Get-PASAccount.md, docs/collections/_commands/Get-PASDiscoveredAccount.md, docs/collections/_commands/Get-PASPSMRecording.md, docs/collections/_commands/Get-PASPSMSession.md, docs/collections/_commands/Get-PASPlatform.md, docs/collections/_commands/Get-PASSession.md, psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/Functions/Accounts/Get-PASDiscoveredAccount.ps1, psPAS/Functions/Authentication/Get-PASSession.ps1, psPAS/Functions/Monitoring/Get-PASPSMRecording.ps1, psPAS/Functions/Monitoring/Get-PASPSMSession.ps1, psPAS/Functions/Platforms/Get-PASPlatform.ps1, psPAS/Private/Invoke-PASRestMethod.ps1, psPAS/en-US/psPAS-help.xml
- `Get-PASPSMRecording`
- Removes `Offset` Parameter
- Updates `FromTime` & `ToTime` parameters to `[datetime]` types
- Returns all pages of results instead of only the first page of results
- `Get-PASPSMSession`
- Removes `Offset` Parameter
- Updates `FromTime` & `ToTime` parameters to `[datetime]` types
- Returns all pages of results instead of only the first page of results
- Removes `Offset` Parameter
- `Get-PASDiscoveredAccount`
- Removes `Offset` Parameter
- `Get-PASSession`
- Removes `UserName` from command output, avoiding error condition on expired session.
- `Get-PASPlatform`
- Adds `search` parameter to the default `targets` parameterset
- ISPSS Error Handling
- Fixes issue where error returned from ISPSS solution may not be handled properly
- 
Fixes #522 …
=> V 6.1 patch1

Tests/New-PASDirectoryMapping.Tests.ps1, Tests/Set-PASDirectoryMapping.Tests.ps1, docs/collections/_commands/New-PASDirectoryMapping.md, docs/collections/_commands/Set-PASDirectoryMapping.md, psPAS/Functions/LDAPDirectories/New-PASDirectoryMapping.ps1, psPAS/Functions/LDAPDirectories/Set-PASDirectoryMapping.ps1
Implements new authentication parameter to existing API/Function. This parameter was released with version 14.4 allowing admins to specify the authentication method allowed with the mapping. 
Implements #570
- CyberArk PAS version: 14.4
=> Added support for new paramter releated to Directory Mappings released with 14.4

docs/collections/_commands/Get-PASPTASecurityConfigurationCategories.md, docs/collections/_commands/Remove-PASPTASecurityConfigurationProperty.md, docs/collections/_commands/Reset-PASPTASecurityConfigurationCategory.md, docs/collections/_commands/Reset-PASPTASecurityConfigurationProperty.md, psPAS/Functions/EventSecurity/Get-PASPTASecurityConfigurationCategories.ps1, psPAS/Functions/EventSecurity/Reset-PASPTASecurityConfigurationProperty.ps1, psPAS/psPAS.psd1
* Added `Get-PASPTASecurityConfigurationCategories` function and documentation
* Added `Reset-PASPTASecurityConfigurationProperty` documentation
* Added `Reset-PASPTASecurityConfigurationCategory` documentation
* Added `Remove-PASPTASecurityConfigurationProperty` documentation
* Fixed some typos
- CyberArk PAS version: 14.6
- OS Version: Windows Server 2022
=> Add new cmdlets for managing PTA security configuration categories and properties. Resolved some typos and added documentation

psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/Functions/Accounts/Get-PASAccountSearchProperty.ps1, psPAS/Private/ConvertTo-FilterString.ps1
Refactor Get-PASAccount to remove external version as this is not acttally needed
Enhance Get-PASAccountSearchProperty to return structured results with valid values and operators
- CyberArk PAS version: 14.6
- OS Version: Windows Server 2022
=> Refactor Get-PASAccount to remove external version as this is not acttally needed

psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/Functions/PTAAdministration/Add-PASPTASMTP.ps1, psPAS/Functions/PTAAdministration/Add-PASPTASyslog.ps1, psPAS/psPAS.psd1
Updated Get-PASAccount to search for props to use for filtering. This commit does not include the new AND,OR,Contains and so on relased with 14.4+! 
* Added a `DynamicParam` block to `Get-PASAccount` that dynamically creates parameters for each available search property from the Get-PASAccountSearchProperty API, applicable to Gen2Query and version 14.4+. This enables users to filter accounts using new properties as soon as they are available so we don't have to hardcode the props in the function itself. 
* Added a new function `Add-PASPTASMTP` to configure SMTP connectivity for PTA 
* Added an alias `Name` for the `siem` parameter in `Add-PASPTASyslog` to increase clarity and ease of use.
I have not tested in versions earlier than 14.6
- …
=> Add dynamic parameters for Get-PASAccount function

docs/collections/_commands/Get-PASAccount.md, psPAS/Functions/Accounts/Get-PASAccount.ps1, psPAS/Functions/Accounts/Get-PASAccountSearchProperty.ps1
Fixes #590 
I believe this issue might have to do with Priv Cloud and there not being support for advanced search parameters as well as LogicalOperator
- CyberArk PAS version: 14.6
- OS Version: Windows Server 2022
=> Update Get-PASAccount and Get-PASAccountSearchProperty to clarify requirements for Self Hosted environments
